name: 'CFN Deploy Stack'
description: "Deploys a CloudFormation stack. Deletes the stack first, if it exists in a bad state."
inputs:
  stackName:
    description: 'Name of the AWS CloudFormation stack to wait for a status on'
    required: true
  templateFilePath:
    description: 'The path to the CloudFormation template file'
    required: true
  awsRegion:
    description: 'AWS Region where the stack is deployed to. Defaults to us-east-1.'
    required: true
    default: "us-east-1"
  tags:
    description: 'The tags to include. Should be a string like "Tag1=Value1 Tag2=Value2"'
    required: false
  parameterOverrides:
    description: 'The parameters to pass into the stack. Should be a string like "Param1=Value1 Param2=Value2"'

runs:
  using: "composite"
  steps:
    - id: add-action-location-to-path
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: |
        # include CloudFormation bash helpers
        source cloud-formation-utils.sh

        # check if the stack exists
        cf_delete_if_bad_state $stackName $awsRegion

        echo Deploying CloudFormation template
        if ! aws cloudformation deploy --template-file "$templateFilePath" \
                --region $awsRegion
                --capabilities CAPABILITY_IAM \
                --stack-name $stackName \
                --tags $tags
                --parameter-overrides $parameterOverrides
        then
          echo Deploy failed.
          cf_print_stack_events $stackName
          # return false to make sure the build stops
          false
        else
          cf_wait_final_status $stackName
          true
        fi
      shell: bash
